### ISSUE TITLE
Mastodonストリーミング中、バックエンドサービスの終了処理でクラッシュ

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#163]
画面遷移を行う時など、バックエンドサービスのバインドが外れて終了処理が走るタイミングでクラッシュする。  
Mastodonのストリーミングチャンネルをどれか1つでも接続している時に発生している。

## Logcat
```
java.lang.Error: java.io.InterruptedIOException: thread interrupted
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.InterruptedIOException: thread interrupted
	at okio.Timeout.throwIfReached(Timeout.java:145)
	at okio.Okio$1.write(Okio.java:76)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.http2.Http2Writer.rstStream(Http2Writer.java:152)
	at okhttp3.internal.http2.Http2Connection.writeSynReset(Http2Connection.java:341)
	at okhttp3.internal.http2.Http2Stream.close(Http2Stream.java:237)
	at okhttp3.internal.http2.Http2Stream.cancelStreamIfNecessary(Http2Stream.java:476)
	at okhttp3.internal.http2.Http2Stream$FramingSource.close(Http2Stream.java:459)
	at okio.ForwardingSource.close(ForwardingSource.java:43)
	at okhttp3.internal.http2.Http2Codec$StreamFinishingSource.close(Http2Codec.java:225)
	at okio.RealBufferedSource.close(RealBufferedSource.java:469)
	at okio.RealBufferedSource$1.close(RealBufferedSource.java:453)
	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:415)
	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:195)
	at java.io.InputStreamReader.close(InputStreamReader.java:199)
	at java.io.BufferedReader.close(BufferedReader.java:536)
	at com.sys1yagi.mastodon4j.api.method.Streaming$user$1.run(Streaming.kt:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	... 2 more
```

**Comment by shibafu528** [comment]
cbc9749244460d4efe02bcef387a9a5c13dc8f3f で修正
