### ISSUE TITLE
OAuth認証のコールバック時にクラッシュ

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#165]
OAuth認証を実施し、コールバックで戻ってきた際にクラッシュ。  
たぶん、OAuthActivity全体でバックエンドサービスの初期化待ちが足りてないんじゃないかな。

## Logcat
```
java.lang.RuntimeException: Unable to resume activity {shibafu.yukari.alpha/shibafu.yukari.activity.OAuthActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'shibafu.yukari.linkage.ProviderApi shibafu.yukari.service.TwitterService.getProviderApi(int)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'shibafu.yukari.linkage.ProviderApi shibafu.yukari.service.TwitterService.getProviderApi(int)' on a null object reference
	at shibafu.yukari.activity.OAuthActivity$MastodonOAuthFragment.finishAuthorize(OAuthActivity.kt:563)
	at shibafu.yukari.activity.OAuthActivity$MastodonOAuthFragment.onResume(OAuthActivity.kt:472)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2294)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1387)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2991)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:6351)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
	... 10 more
```

**Comment by tateisu** [comment]
開発者オプションの「アクティビティを保持しない」は試した方がいいと思います
