### ISSUE TITLE
UserUpdateDelayerがシャットダウンされていない

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#168]
UserUpdateDelayerがシャットダウンされていないため、アプリのライフサイクルが終了して後にDBが開かれているつもりで操作しようとしてクラッシュしている。  
ただ、そもそもUUDがこんな場所に参照置かれていていいの…？とか、ちょっと考えたいことがあるので、後々まとめる。

## Logcat
```
08-19 01:09:58.501 23259-23325/shibafu.yukari.alpha E/AndroidRuntime: FATAL EXCEPTION: UserUpdateDelayer
    Process: shibafu.yukari.alpha, PID: 23259
    java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/shibafu.yukari.alpha/databases/yukari.db
        at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
        at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:503)
        at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
        at shibafu.yukari.database.CentralDatabase.beginTransaction(CentralDatabase.java:643)
        at shibafu.yukari.twitter.statusmanager.UserUpdateDelayer$Worker.run(UserUpdateDelayer.java:57)
        at java.lang.Thread.run(Thread.java:818)
```

## 注釈: UserUpdateDelayerとは
DBのUserテーブルに記録されているユーザ情報のキャッシュを、UserStreamの着信から最新のユーザ情報を抜き取り適度にキューしつつ更新するためのクラス。  
実装自体はy4a 2.0までのものがそのまま使われている状態なので、2.1移行の共通インターフェースのための修正などは、本チケット起票時点では行われていない。

**Comment by shibafu528** [comment]
10/22時点の考えをメモしておきます。

## 直近の方針
UserUpdateDelayerはTwitterStream.ktで管理する。ここであれば、コアサービスのシャットダウンイベントを取れるので2.0当時と同程度の安全性で停止することができる。

## 中長期的な方針
Userテーブルのデータは取得元のサービスのAPIレスポンス構造にべったり依存している。これを無闇に汎用化するのも、情報を落としたりすることになるので微妙。  
だったら、UserテーブルはTwitter用のままに、UserUpdateDelayerもそのままTwitter用のものとして据え置く。  
Mastodonのユーザをキャッシュしたくなったら、Mastodonに適したテーブル構造や保存処理を別途作り込む。  
こうしておけば、各サービスにデータの持ち方の詳細を任せることができる。

ユーザ検索の候補表示のような場所で、横断して使いたい場所には別途インターフェースを作成する。例えば、各サービスのAPIProviderに同じ検索クエリを飛ばして、Userインターフェースで返してもらうとか。
