### ISSUE TITLE
ネットワーク切断時にクラッシュする？

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#200]
詳細な状況についてのレポートがないのと手元再現がとれていないので不確定ですが、Mastodonのストリーミング使用中にネットワーク切断を契機にクラッシュするケースがまだあるみたいです。

## 環境
| | |
| ---- | ---- |
| Yukari | 2.1.0.1713-dev (linkage 181118 760214b) |
| OS | Android 8.0.0 |
| Device | Samsung Galaxy S9+ SCV39 |

## Logcat
```
11-22 09:06:11.985  /  AndroidRuntime:
FATAL EXCEPTION: Thread-13
Process: shibafu.yukari.alpha, PID: 18233
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 592 path $.account.null
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.sys1yagi.mastodon4j.api.method.Streaming.receiveUser(Streaming.kt:173)
	at com.sys1yagi.mastodon4j.api.method.Streaming.access$receiveUser(Streaming.kt:17)
	at com.sys1yagi.mastodon4j.api.method.Streaming$connect$1.run(Streaming.kt:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.EOFException: End of input at line 1 column 592 path $.account.null
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 9 more

11-22 09:06:11.985  /  AndroidRuntime:
FATAL EXCEPTION: Thread-15
Process: shibafu.yukari.alpha, PID: 18233
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 257 path $.uri
	at com.google.gson.Gson.fromJson(Gson.java:902)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.sys1yagi.mastodon4j.api.method.Streaming.receiveUser(Streaming.kt:173)
	at com.sys1yagi.mastodon4j.api.method.Streaming.access$receiveUser(Streaming.kt:17)
	at com.sys1yagi.mastodon4j.api.method.Streaming$connect$1.run(Streaming.kt:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 257 path $.uri
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:401)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:389)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 9 more

11-22 09:06:11.985  /  AndroidRuntime:
FATAL EXCEPTION: Thread-14
Process: shibafu.yukari.alpha, PID: 18233
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 1676 path $.account.emojis[1].shortcode
	at com.google.gson.Gson.fromJson(Gson.java:902)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.sys1yagi.mastodon4j.api.method.Streaming.receiveUser(Streaming.kt:173)
	at com.sys1yagi.mastodon4j.api.method.Streaming.access$receiveUser(Streaming.kt:17)
	at com.sys1yagi.mastodon4j.api.method.Streaming$connect$1.run(Streaming.kt:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 1676 path $.account.emojis[1].shortcode
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:76)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:70)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 9 more
```

以下はこのクラッシュと同時刻に発生していた、Twitterストリーミング処理系のログ。t4jだとGzip展開処理がコケて例外処理されているみたい。参考までに。

```
11-22 09:06:11.994  /  System.err:
Stream closed.
Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=a8fd061d or
	http://www.google.co.jp/search?q=00089f66
TwitterException{exceptionCode=[a8fd061d-00089f66 a8fd061d-00089edd], statusCode=-1, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}

18233 18356 W11-22 09:06:11.995  /  System.err:
	at twitter4j.StatusStreamBase.handleNextElement(StatusStreamBase.java:212)
	at twitter4j.StatusStreamImpl.next(StatusStreamImpl.java:56)
	at twitter4j.TwitterStreamImpl$TwitterStreamConsumer.run(TwitterStreamImpl.java:586)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:252)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:163)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:172)
	at java.io.BufferedReader.readLine(BufferedReader.java:335)
	at java.io.BufferedReader.readLine(BufferedReader.java:400)
	at twitter4j.StatusStreamBase.handleNextElement(StatusStreamBase.java:75)
	... 2 more
```

**Comment by shibafu528** [comment]
Mastodonのストリーミング実装を差し替えたので一旦close。
