### ISSUE TITLE
フォロー管理ダイアログを出した状態でタスクを切り替えると復帰時に落ちる

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#201]
## 概要
「アクティビティを保持しない」を有効にした環境で、フォロー管理ダイアログを出した状態でホームに戻り、タスク履歴から再表示するとクラッシュ。

## 環境
| | |
| ---- | ---- |
| Yukari | 2.1.0.1726-dev (linkage 181128 39fcbe9) |
| OS | Android 8.0.0 |
| Device | ASUS Zenfone 3 Z017DA |

## Logcat 
```
11-28 23:57:34.992 23562-23562/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: shibafu.yukari.alpha, PID: 23562
    java.lang.RuntimeException: Unable to start activity ComponentInfo{shibafu.yukari.alpha/shibafu.yukari.activity.ProfileActivity}: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.LinkedHashMap
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2827)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2902)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6578)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.LinkedHashMap
        at shibafu.yukari.fragment.FollowDialogFragment.onCreateDialog(FollowDialogFragment.java:91)
        at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:310)
        at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1231)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7033)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2902) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:169) 
        at android.app.ActivityThread.main(ActivityThread.java:6578) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by shibafu528** [comment]
LinkedHashMapをBundleに入れると、HashMapとしてシリアライズされてしまうみたい。  
大人しく配列とかリストとか、順序を保てるデータ構造に落としこむしかなさそう？
