### ISSUE TITLE
TLを見ていると `trying to use a recycled bitmap` で落ちる

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#332]
TLを見ているだけで落ちることがある。

## backtrace

```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@58fc964
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:74)
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:263)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at android.view.View.draw(View.java:23209)
	at android.view.View.updateDisplayListIfDirty(View.java:22076)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23212)
	at android.view.View.updateDisplayListIfDirty(View.java:22076)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.widget.ListView.drawChild(ListView.java:3613)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2735)
	at android.widget.ListView.dispatchDraw(ListView.java:3608)
	at android.view.View.draw(View.java:23212)
	at android.widget.AbsListView.draw(AbsListView.java:4527)
	at android.view.View.updateDisplayListIfDirty(View.java:22076)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23212)
	at android.view.View.updateDisplayListIfDirty(View.java:22076)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23212)
	at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
	at android.view.View.updateDisplayListIfDirty(View.java:22076)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22067)
	at android.view.View.draw(View.java:22940)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23212)
	at com.android.internal.policy.DecorView.draw(DecorView.java:836)
	at android.view.View.updateDisplayListIfDirty(View.java:22076)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4582)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3520)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2289)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8958)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1319)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1327)
	at android.view.Choreographer.doCallbacks(Choreographer.java:985)
	at android.view.Choreographer.doFrame(Choreographer.java:916)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1302)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by shibafu528** [comment]
おそらくこの `recycle()` が原因。直前の処理でBitmapCache (オンメモリキャッシュ) に格納したBitmapインスタンスを解放している。

https://github.com/shibafu528/Yukari/blob/8696617a669a1cb36e6d3821c7bf79b063a50d28/Yukari/src/main/java/shibafu/yukari/common/bitmapcache/ImageLoaderTask.java#L110-L117

**Comment by shibafu528** [comment]
git blameが正しければ #1 で導入された9年もののバグ。
